import { buildRealtimeInstructions } from '../interview-content/instructions';
import { createInitialProgress, phaseAt } from '../interview-content/progress';
import type { InterviewProgress } from '../interview-content/types';
import type { RealtimeConnection, VoiceEvent } from '../realtime-voice/port';
import type { InterviewSession, InterviewSessionDependencies, InterviewSessionView, SessionState } from './types';

const HINT=8_000, RESPONSE=15_000, RECONNECT=20_000, CADENCE=2_000, DRAIN=5_000, CUTOFF=2_430_000, SOFT=2_700_000, HARD=2_820_000;
type Recent={speaker:'candidate'|'ai';text:string;providerTurnId:string};
function defaultSummary(input:{progress:InterviewProgress;finalTurnCount:number;phase:InterviewProgress['phase'];recentTurns:Recent[]}):InterviewProgress { const r=input.recentTurns.slice(-8); return {...input.progress,phase:input.phase,updatedThroughSequence:input.finalTurnCount,coveredTopics:r.map(x=>x.text.replace(/\s+/g,' ').slice(0,80)),evidence:r.filter(x=>x.speaker==='candidate').map(x=>({claim:x.text.slice(0,120),observation:'候选人最终回答',turnIds:[x.providerTurnId]})),pendingFollowUps:r.filter(x=>x.speaker==='candidate').slice(-3).map(x=>`追问：${x.text.slice(0,80)}`)}; }

export function createInterviewSession(deps:InterviewSessionDependencies):InterviewSession {
 let state:SessionState='ready', result:InterviewSessionView['result']=null, error:string|null=null, id:string|null=null, connection:RealtimeConnection|null=null, unsub:(()=>void)|null=null;
 let activeSince:number|null=null, active=0, sequence=0, candidate=false, gap=false, finalizing=false, progress=createInitialProgress(), hint=false, retried=false, allow=true, epoch=0, connecting=false;
 const pendingTurns=new Set<string>();
 const recent:Recent[]=[], closed=new WeakSet<RealtimeConnection>();
 let hintC:(()=>void)|null=null,responseC:(()=>void)|null=null,reconnectC:(()=>void)|null=null,cadenceC:(()=>void)|null=null,budgetC:(()=>void)|null=null,drainC:(()=>void)|null=null, queue=Promise.resolve(), running=false;
 const clear=(x:(()=>void)|null)=>x?.(), elapsed=()=>active+(activeSince===null?0:deps.clock.now()-activeSince), phase=()=>phaseAt(elapsed());
 const pause=()=>{if(activeSince!==null){active+=deps.clock.now()-activeSince;activeSince=null;}clear(budgetC);budgetC=null;};
 const enqueue=(f:()=>Promise<void>)=>{const work=running?queue.then(f,f):f();running=true;const tracked=work.catch(()=>{error='会话操作失败';if(!result){state='paused';pause();}});queue=tracked;void tracked.finally(()=>{if(queue===tracked)running=false;});return tracked;};
 const clearResponse=()=>{clear(hintC);clear(responseC);hintC=responseC=null;hint=false;};
 const view=():InterviewSessionView=>({state,result,activeDurationMs:elapsed(),allowNewTopics:allow,responseHint:hint,error});
 async function safeClose(c:RealtimeConnection|null){if(!c||closed.has(c))return;closed.add(c);try{await c.close();}catch{error='语音连接关闭失败';}}
 async function inject(){if(!connection)return;try{progress=(deps.summarizeProgress??defaultSummary)({progress,finalTurnCount:sequence,phase:phase(),recentTurns:recent});await connection.injectProgress(progress);}catch{error='进度更新失败，将在下次检查点重试';}}
 function scheduleBudget(){clear(budgetC);const next=[300000,1200000,1920000,CUTOFF,2520000,SOFT,HARD].find(x=>x>elapsed());if(next)budgetC=deps.scheduler.schedule(()=>void enqueue(budget),next-elapsed());}
 const resume=()=>{if(activeSince===null&&!result){activeSince=deps.clock.now();scheduleBudget();}};
 async function finalize(wanted:NonNullable<InterviewSessionView['result']>,missing:boolean){if(result||finalizing||!id)return;finalizing=true;clearResponse();clear(reconnectC);clear(cadenceC);clear(drainC);pause();epoch++;await safeClose(connection);const terminal=wanted==='completed'&&!candidate?'cancelled':wanted;try{await deps.history.finish(id,terminal,gap||missing||pendingTurns.size>0?'missing':'complete',active);result=terminal;state='finished';unsub?.();unsub=null;}catch{finalizing=false;error='保存会话结果失败';state='paused';}}
 function drain(manual=false){state='closing';if(pendingTurns.size===0){if(manual)void enqueue(()=>finalize(candidate?'completed':'cancelled',false));return;}clear(drainC);drainC=deps.scheduler.schedule(()=>void enqueue(()=>finalize(candidate?'completed':'cancelled',true)),DRAIN);}
 async function budget(){if(result||activeSince===null)return;const before=progress.phase,now=elapsed();if(now>=CUTOFF)allow=false;if(now>=HARD){await finalize(candidate?'completed':'cancelled',pendingTurns.size>0);return;}if(now>=SOFT)drain();scheduleBudget();if(phase()!==before)await inject();}
 async function attempt(token:number){if(connecting||result)return;connecting=true;try{const next=await deps.voice.connect({instructions:buildRealtimeInstructions(deps.snapshot,progress),resumeFromSequence:sequence});if(token!==epoch||result){await safeClose(next);return;}const old=connection;unsub?.();connection=next;unsub=next.subscribe(input=>enqueue(async()=>{if(token===epoch&&!result)await onEvent(input);}));if(old&&old!==next)await safeClose(old);clear(reconnectC);clear(cadenceC);await inject();state=elapsed()>=SOFT?'closing':'listening';resume();}catch{if(token===epoch&&!result)error='正在重连语音服务';}finally{connecting=false;}}
 function reconnect():Promise<void>{if(result||state==='reconnecting')return Promise.resolve();clearResponse();pause();state='reconnecting';const token=++epoch;unsub?.();unsub=null;void safeClose(connection);clear(reconnectC);reconnectC=deps.scheduler.schedule(()=>void enqueue(()=>finalize('interrupted',pendingTurns.size>0)),RECONNECT);const tick=()=>{if(token!==epoch||result)return;void attempt(token);cadenceC=deps.scheduler.schedule(tick,CADENCE);};cadenceC=deps.scheduler.schedule(tick,CADENCE);return attempt(token);}
 function timeout(){clearResponse();hintC=deps.scheduler.schedule(()=>{hint=true;},HINT);responseC=deps.scheduler.schedule(()=>{if(retried){state='paused';pause();}else{retried=true;reconnect();}},RESPONSE);}
 async function onEvent(e:VoiceEvent){if(result||finalizing)return;switch(e.type){case'connection':if(e.state==='disconnected')reconnect();break;case'transcript':pendingTurns.add(e.providerTurnId);break;case'candidate_speech':if(e.state==='started'){retried=false;clearResponse();if(state==='speaking')try{await connection?.cancelAssistantSpeech();if(result||finalizing)return;state='listening';}catch{error='打断失败，可重试';state='paused';pause();}else state='listening';}else timeout();break;case'assistant_speech':clearResponse();retried=false;state=e.state==='started'?'speaking':'listening';break;case'response':if(e.state==='started'){clearResponse();state='thinking';}else if(state==='thinking'){retried=false;state='listening';}break;case'error':if(e.category==='ai_unavailable')reconnect();else await finalize('interrupted',pendingTurns.size>0);break;case'final_turn':if(!id)return;const out=await deps.history.appendFinalTurn({sessionId:id,providerTurnId:e.providerTurnId,sequence:sequence+1,speaker:e.speaker,text:e.text,startedAt:e.startedAt,endedAt:e.endedAt,hasGap:e.hasGap});if(result||finalizing)return;if(out==='inserted'){sequence++;candidate ||= e.speaker==='candidate';gap ||= !!e.hasGap;recent.push({speaker:e.speaker,text:e.text,providerTurnId:e.providerTurnId});pendingTurns.delete(e.providerTurnId);if(sequence%10===0)await inject();}if(state==='closing'&&pendingTurns.size===0)await finalize(candidate?'completed':'cancelled',false);break;}}
 async function end(){await enqueue(async()=>{if(result)return;drain(true);});}
 return {view,async start(devices){if(!devices.microphone||!devices.camera)throw new Error('microphone and camera are required');if(state!=='ready')throw new Error('session has already started');state='connecting';const token=++epoch;try{const next=await deps.voice.connect({instructions:buildRealtimeInstructions(deps.snapshot,progress),resumeFromSequence:0});if(token!==epoch){await safeClose(next);return;}connection=next;try{id=await deps.history.start({startedAt:deps.clock.now(),targetDurationMs:SOFT,snapshot:deps.snapshot});}catch(cause){await safeClose(next);connection=null;state='ready';throw cause;}unsub=next.subscribe(e=>enqueue(async()=>{if(token===epoch&&!result&&!finalizing)await onEvent(e);}));state='listening';resume();}catch(cause){if(state==='connecting')state='ready';throw cause;}},async retry(){await enqueue(async()=>{if(state==='paused'){retried=false;clearResponse();state='ready';await reconnect();}});},async signalEndOfAnswer(){try{await connection?.signalEndOfAnswer();}catch{error='结束回答辅助失败';}},end};
}
